export const skillsData = [
  { skill: 'HTML', count: 30 },
  { skill: 'CSS', count: 35 },
  { skill: 'JavaScript', count: 40 },
  { skill: 'React', count: 25 },
  { skill: 'Angular', count: 20 },
  { skill: 'Vue.js', count: 30 },
  { skill: 'Node.js', count: 35 },
  { skill: 'Express.js', count: 15 },
  { skill: 'Django', count: 20 },
  { skill: 'Flask', count: 10 },
  { skill: 'Python', count: 15 },
  { skill: 'Ruby', count: 10 },
  { skill: 'Ruby on Rails', count: 5 },
  { skill: 'Java', count: 30 },
  { skill: 'Spring Boot', count: 10 },
  { skill: 'Kotlin', count: 12 },
  { skill: 'Swift', count: 25 },
  { skill: 'Objective-C', count: 20 },
  { skill: 'iOS Development', count: 15 },
  { skill: 'Android Development', count: 10 },
  { skill: 'Firebase', count: 8 },
  { skill: 'AWS', count: 5 },
  { skill: 'Google Cloud Platform', count: 15 },
  { skill: 'Microsoft Azure', count: 10 },
  { skill: 'Docker', count: 12 },
  { skill: 'Kubernetes', count: 8 },
  { skill: 'Git', count: 6 },
  { skill: 'GitHub', count: 10 },
  { skill: 'Bitbucket', count: 12 },
  { skill: 'Jira', count: 8 },
  { skill: 'Confluence', count: 6 },
  { skill: 'Slack', count: 10 },
  { skill: 'Trello', count: 12 },
  { skill: 'PostgreSQL', count: 8 },
  { skill: 'MySQL', count: 6 },
  { skill: 'MongoDB', count: 10 },
  { skill: 'SQLite', count: 12 },
  { skill: 'Redis', count: 8 },
  { skill: 'Elasticsearch', count: 6 },
  { skill: 'GraphQL', count: 10 },
  { skill: 'REST API', count: 12 },
  { skill: 'JSON', count: 8 },
  { skill: 'XML', count: 6 },
  { skill: 'OAuth', count: 10 },
  { skill: 'JWT', count: 12 },
  { skill: 'SASS', count: 8 },
  { skill: 'LESS', count: 6 },
  { skill: 'Bootstrap', count: 10 },
  { skill: 'Tailwind CSS', count: 12 },
  { skill: 'Material-UI', count: 8 },
  { skill: 'Ant Design', count: 6 },
  { skill: 'Redux', count: 10 },
  { skill: 'MobX', count: 12 },
  { skill: 'RxJS', count: 8 },
  { skill: 'Webpack', count: 6 },
  { skill: 'Babel', count: 10 },
  { skill: 'ESLint', count: 12 },
  { skill: 'Prettier', count: 8 },
  { skill: 'npm', count: 6 },
  { skill: 'yarn', count: 10 },
  { skill: 'CI/CD', count: 12 },
  { skill: 'TDD', count: 8 },
  { skill: 'BDD', count: 6 },
  { skill: 'Unit Testing', count: 10 },
  { skill: 'Integration Testing', count: 12 },
  { skill: 'End-to-End Testing', count: 8 },
  { skill: 'Cypress', count: 6 },
  { skill: 'Jest', count: 10 },
  { skill: 'Mocha', count: 12 },
  { skill: 'Chai', count: 8 },
  { skill: 'Karma', count: 6 },
  { skill: 'SEO', count: 10 },
  { skill: 'Social Media Marketing', count: 12 },
  { skill: 'Email Marketing', count: 8 },
  { skill: 'Content Marketing', count: 6 },
  { skill: 'Google Ads', count: 10 },
  { skill: 'Keyword Research', count: 12 },
  { skill: 'On-Page SEO', count: 8 },
  { skill: 'Off-Page SEO', count: 6 },
  { skill: 'Google Analytics', count: 10 },
  { skill: 'SEO Tools', count: 12 },
  { skill: 'Cisco', count: 8 },
  { skill: 'LAN/WAN', count: 6 },
  { skill: 'TCP/IP', count: 10 },
  { skill: 'Routing', count: 12 },
  { skill: 'Network Security', count: 8 },
  { skill: 'Troubleshooting', count: 6 },
  { skill: 'SQL', count: 10 },
  { skill: 'Database Management', count: 12 },
  { skill: 'Database Design', count: 8 },
  { skill: 'Backup and Recovery', count: 6 },
  { skill: 'Data Security', count: 10 },
  { skill: 'System Analysis', count: 12 },
  { skill: 'Requirement Gathering', count: 8 },
  { skill: 'UML', count: 6 },
  { skill: 'System Design', count: 10 },
  { skill: 'Agile', count: 12 },
  { skill: 'Cybersecurity', count: 8 },
  { skill: 'Penetration Testing', count: 6 },
  { skill: 'Security Policies', count: 10 },
  { skill: 'Encryption', count: 12 },
];
